stacks = [[{'frame': 0,
   'function': 'static long patched_LdrLoadDll(wchar_t *, unsigned long *, '
               'struct _UNICODE_STRING *, void * *)',
   'function_offset': '0x1ec',
   'module': 'mozglue.pdb',
   'module_offset': '0x52bc'},
  {'frame': 1,
   'function': 'NlsConvertStringToIntegerW',
   'function_offset': '0x2eb6',
   'module': 'kernelbase.pdb',
   'module_offset': '0x20176'},
  {'frame': 2,
   'function': 'NSPROVIDER::Initialize(unsigned short *,_GUID *,unsigned long)',
   'function_offset': '0x5b',
   'module': 'ws2_32.pdb',
   'module_offset': '0x5c5b'},
  {'frame': 3,
   'function': 'NSCATALOG::LoadProvider(NSCATALOGENTRY *)',
   'function_offset': '0x8c',
   'module': 'ws2_32.pdb',
   'module_offset': '0x5bac'},
  {'frame': 4,
   'function': 'DCATALOG::FindAnotherProviderInstance(_GUID *)',
   'function_offset': '0x86',
   'module': 'ws2_32.pdb',
   'module_offset': '0x5ae6'},
  {'frame': 5,
   'function': 'NSQUERY::LookupServiceBegin(_WSAQuerySetW *,unsigned '
               'long,NSCATALOG *)',
   'function_offset': '0x19a',
   'module': 'ws2_32.pdb',
   'module_offset': '0x321a'},
  {'frame': 6,
   'function': 'WSALookupServiceBeginW',
   'function_offset': '0xd8',
   'module': 'ws2_32.pdb',
   'module_offset': '0x3038'},
  {'frame': 7,
   'function': 'WSALookupServiceBeginA',
   'function_offset': '0xa4',
   'module': 'ws2_32.pdb',
   'module_offset': '0xa794'},
  {'frame': 8,
   'function': 'getxyDataEnt(char * *,unsigned long,char *,_GUID *,char * *)',
   'function_offset': '0x84',
   'module': 'ws2_32.pdb',
   'module_offset': '0x9f64'},
  {'frame': 9,
   'function': 'gethostname',
   'function_offset': '0xb7',
   'module': 'ws2_32.pdb',
   'module_offset': '0xab97'},
  {'frame': 10,
   'function': 'mozilla::net::nsSocketTransportService::Run()',
   'function_offset': '0xc4',
   'module': 'xul.pdb',
   'module_offset': '0x4ea84'},
  {'frame': 11,
   'function': 'nsThread::ProcessNextEvent(bool,bool *)',
   'function_offset': '0x59f',
   'module': 'xul.pdb',
   'module_offset': '0x4ad0f'},
  {'frame': 12,
   'function': 'NS_ProcessNextEvent(nsIThread *,bool)',
   'function_offset': '0x29',
   'module': 'xul.pdb',
   'module_offset': '0x4a6a9'},
  {'frame': 13,
   'function': 'mozilla::ipc::MessagePumpForNonMainThreads::Run(base::MessagePump::Delegate '
               '*)',
   'function_offset': '0x134',
   'module': 'xul.pdb',
   'module_offset': '0x4a414'},
  {'frame': 14,
   'function': 'MessageLoop::RunHandler()',
   'function_offset': '0x28',
   'module': 'xul.pdb',
   'module_offset': '0x24ba8'},
  {'frame': 15,
   'function': 'static void nsThread::ThreadFunc(void *)',
   'function_offset': '0x1fd',
   'module': 'xul.pdb',
   'module_offset': '0x497ad'},
  {'frame': 16,
   'function': 'static void _PR_NativeRunThread(void *)',
   'function_offset': '0x14a',
   'module': 'nss3.pdb',
   'module_offset': '0x13c51a'},
  {'frame': 17,
   'function': 'unsigned int pr_root(void *)',
   'function_offset': '0xa',
   'module': 'nss3.pdb',
   'module_offset': '0x12c0fa'},
  {'frame': 18,
   'function': 'o_strcat_s',
   'function_offset': '0x5e',
   'module': 'ucrtbase.pdb',
   'module_offset': '0x1c1ae'},
  {'frame': 19,
   'module': 'ucrtbase.pdb',
   'module_offset': '-0x8000000000000000'}],
 [{'frame': 0,
   'function': 'static long patched_LdrLoadDll(wchar_t *, unsigned long *, '
               'struct _UNICODE_STRING *, void * *)',
   'function_offset': '0x1ec',
   'module': 'ucrtbase.pdb',
   'module_offset': '0x52bc'},
  {'frame': 1,
   'function': 'NlsConvertStringToIntegerW',
   'function_offset': '0x2eb6',
   'module': 'ucrtbase.pdb',
   'module_offset': '0x20176'},
  {'frame': 2,
   'function': 'LoadLibraryWithLogging(LoadOrFreeWhy,unsigned short const '
               '*,unsigned long,HINSTANCE__ * *)',
   'function_offset': '0x2e',
   'module': 'ole32.pdb',
   'module_offset': '0x147ae'},
  {'frame': 3,
   'function': 'CClassCache::CDllPathEntry::LoadDll(DLL_INSTANTIATION_PROPERTIES '
               '&,long (*&)(_GUID const &,_GUID const &,void * *),long '
               '(*&)(void),HINSTANCE__ * &)',
   'function_offset': '0x5b',
   'module': 'ole32.pdb',
   'module_offset': '0x14723'},
  {'frame': 4,
   'function': 'CClassCache::CDllPathEntry::Create_rl(DLL_INSTANTIATION_PROPERTIES '
               '&,ACTIVATION_PROPERTIES const &,CClassCache::CDllPathEntry * '
               '&)',
   'function_offset': '0x4c',
   'module': 'ole32.pdb',
   'module_offset': '0x14528'},
  {'frame': 5,
   'function': 'CClassCache::CClassEntry::CreateDllClassEntry_rl(unsigned '
               'long,ACTIVATION_PROPERTIES const &,CClassCache::CDllClassEntry '
               '* &)',
   'function_offset': '0xe1',
   'module': 'ole32.pdb',
   'module_offset': '0x11661'},
  {'frame': 6,
   'function': 'CClassCache::GetClassObjectActivator(unsigned '
               'long,ACTIVATION_PROPERTIES const &,CClassCache::IMiniMoniker * '
               '*)',
   'function_offset': '0x72',
   'module': 'ole32.pdb',
   'module_offset': '0x11527'},
  {'frame': 7,
   'function': 'CClassCache::GetClassObject(ACTIVATION_PROPERTIES const &)',
   'function_offset': '0x45',
   'module': 'ole32.pdb',
   'module_offset': '0x11de5'},
  {'frame': 8,
   'function': 'CServerContextActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x178',
   'module': 'ole32.pdb',
   'module_offset': '0x11ca8'},
  {'frame': 9,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x5e',
   'module': 'ole32.pdb',
   'module_offset': '0x1105a'},
  {'frame': 10,
   'function': 'CApartmentActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x88',
   'module': 'ole32.pdb',
   'module_offset': '0x112ec'},
  {'frame': 11,
   'function': 'CProcessActivator::CCICallback(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x4e',
   'module': 'ole32.pdb',
   'module_offset': '0x1135e'},
  {'frame': 12,
   'function': 'CProcessActivator::AttemptActivation(ActivationPropertiesIn '
               '*,IUnknown *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *,long ( '
               'CProcessActivator::*)(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *),unsigned long)',
   'function_offset': '0x33',
   'module': 'ole32.pdb',
   'module_offset': '0x3649f'},
  {'frame': 13,
   'function': 'CProcessActivator::ActivateByContext(ActivationPropertiesIn '
               '*,IUnknown *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *,long ( '
               'CProcessActivator::*)(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *))',
   'function_offset': '0x7f',
   'module': 'ole32.pdb',
   'module_offset': '0x3643f'},
  {'frame': 14,
   'function': 'CProcessActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x77',
   'module': 'ole32.pdb',
   'module_offset': '0x11f1b'},
  {'frame': 15,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x5e',
   'module': 'ole32.pdb',
   'module_offset': '0x1105a'},
  {'frame': 16,
   'function': 'CClientContextActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0xef',
   'module': 'ole32.pdb',
   'module_offset': '0x11167'},
  {'frame': 17,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x5e',
   'module': 'ole32.pdb',
   'module_offset': '0x1105a'},
  {'frame': 18,
   'function': 'ICoCreateInstanceEx(_GUID const &,IUnknown *,unsigned '
               'long,_COSERVERINFO *,unsigned long,unsigned long,tagMULTI_QI '
               '*,ActivationPropertiesIn *)',
   'function_offset': '0x19c',
   'module': 'ole32.pdb',
   'module_offset': '0x11a50'},
  {'frame': 19,
   'function': 'CoCreateInstance',
   'function_offset': '0x17b',
   'module': 'ole32.pdb',
   'module_offset': '0x26e8b'},
  {'frame': 20,
   'function': 'CDesktopFolder::_GetFolderForParsing(unsigned short const '
               '*,IBindCtx *,IShellFolder * *,_ITEMIDLIST_ABSOLUTE * *)',
   'function_offset': '0x1c5',
   'module': 'shell32.pdb',
   'module_offset': '0x85135'},
  {'frame': 21,
   'function': 'SHExtCoCreateInstance',
   'function_offset': '0x28',
   'module': 'shell32.pdb',
   'module_offset': '0x6a810'},
  {'frame': 22,
   'function': 'DCA_SHExtCoCreateInstance',
   'function_offset': '0x41',
   'module': 'shell32.pdb',
   'module_offset': '0x4dd71'},
  {'frame': 23,
   'function': 'CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers(CDSA<_GUID> '
               'const *,CDSA<FSIconOverlay> *)',
   'function_offset': '0x11c',
   'module': 'shell32.pdb',
   'module_offset': '0x25ccc'},
  {'frame': 24,
   'function': 'CFSIconOverlayManager::CreateInstance(IUnknown *,_GUID const '
               '&,void * *)',
   'function_offset': '0x80',
   'module': 'shell32.pdb',
   'module_offset': '0x25b74'},
  {'frame': 25,
   'function': 'QueryNewMaxIcons()',
   'function_offset': '0x118',
   'module': 'shell32.pdb',
   'module_offset': '0x25ac8'},
  {'frame': 26,
   'function': 'GetIconOverlayManager',
   'function_offset': '0x1b',
   'module': 'shell32.pdb',
   'module_offset': '0x4256b'},
  {'frame': 27,
   'function': 'CShellExecute::Release()',
   'function_offset': '0x338',
   'module': 'shell32.pdb',
   'module_offset': '0x28020'},
  {'frame': 28,
   'function': 'vsnwprintf',
   'function_offset': '0xb62f',
   'module': 'shell32.pdb',
   'module_offset': '0x1b236b'},
  {'frame': 29,
   'function': 'CDragDropHelper_CreateInstance',
   'function_offset': '0x15',
   'module': 'shell32.pdb',
   'module_offset': '0x6b5c5'},
  {'frame': 30,
   'function': 'CCF_CreateInstance',
   'function_offset': '0x26',
   'module': 'shell32.pdb',
   'module_offset': '0xa2eae'},
  {'frame': 31,
   'function': 'CServerContextActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x1f3',
   'module': 'shell32.pdb',
   'module_offset': '0x11d23'},
  {'frame': 32,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x5e',
   'module': 'shell32.pdb',
   'module_offset': '0x1105a'},
  {'frame': 33,
   'function': 'CApartmentActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x88',
   'module': 'shell32.pdb',
   'module_offset': '0x112ec'},
  {'frame': 34,
   'function': 'CProcessActivator::CCICallback(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x4e',
   'module': 'shell32.pdb',
   'module_offset': '0x1135e'},
  {'frame': 35,
   'function': 'CProcessActivator::AttemptActivation(ActivationPropertiesIn '
               '*,IUnknown *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *,long ( '
               'CProcessActivator::*)(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *),unsigned long)',
   'function_offset': '0x33',
   'module': 'shell32.pdb',
   'module_offset': '0x3649f'},
  {'frame': 36,
   'function': 'CProcessActivator::ActivateByContext(ActivationPropertiesIn '
               '*,IUnknown *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *,long ( '
               'CProcessActivator::*)(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *))',
   'function_offset': '0x7f',
   'module': 'shell32.pdb',
   'module_offset': '0x3643f'},
  {'frame': 37,
   'function': 'CProcessActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x77',
   'module': 'shell32.pdb',
   'module_offset': '0x11f1b'},
  {'frame': 38,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x5e',
   'module': 'shell32.pdb',
   'module_offset': '0x1105a'},
  {'frame': 39,
   'function': 'CClientContextActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0xef',
   'module': 'shell32.pdb',
   'module_offset': '0x11167'},
  {'frame': 40,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x5e',
   'module': 'shell32.pdb',
   'module_offset': '0x1105a'},
  {'frame': 41,
   'function': 'ICoCreateInstanceEx(_GUID const &,IUnknown *,unsigned '
               'long,_COSERVERINFO *,unsigned long,unsigned long,tagMULTI_QI '
               '*,ActivationPropertiesIn *)',
   'function_offset': '0x19c',
   'module': 'shell32.pdb',
   'module_offset': '0x11a50'},
  {'frame': 42,
   'function': 'CoCreateInstance',
   'function_offset': '0x17b',
   'module': 'shell32.pdb',
   'module_offset': '0x26e8b'},
  {'frame': 43,
   'function': 'nsDragService::InvokeDragSessionImpl(nsIArray '
               '*,mozilla::Maybe<mozilla::gfx::IntRegionTyped<mozilla::CSSPixel> '
               '> const &,unsigned int)',
   'function_offset': '0x34f',
   'module': 'shell32.pdb',
   'module_offset': '0x389aedf'},
  {'frame': 44,
   'function': 'nsBaseDragService::InvokeDragSession(nsINode *,nsIPrincipal '
               '*,nsIArray *,unsigned int,unsigned int)',
   'function_offset': '0x1c1',
   'module': 'shell32.pdb',
   'module_offset': '0x380c7b1'},
  {'frame': 45,
   'function': 'nsBaseDragService::InvokeDragSessionWithImage(nsINode '
               '*,nsIPrincipal *,nsIArray *,unsigned int,nsINode '
               '*,int,int,mozilla::dom::DragEvent *,mozilla::dom::DataTransfer '
               '*)',
   'function_offset': '0x17a',
   'module': 'shell32.pdb',
   'module_offset': '0x380ca1a'},
  {'frame': 46,
   'function': 'bool mozilla::EventStateManager::DoDefaultDragStart(class '
               'nsPresContext *, class mozilla::WidgetDragEvent *, class '
               'mozilla::dom::DataTransfer *, class nsIContent *, class '
               'mozilla::dom::Selection *, class nsIPrincipal *)',
   'function_offset': '0x20f',
   'module': 'shell32.pdb',
   'module_offset': '0x307d3ef'},
  {'frame': 47,
   'function': 'void mozilla::EventStateManager::GenerateDragGesture(class '
               'nsPresContext *, class mozilla::WidgetInputEvent *)',
   'function_offset': '0x6db',
   'module': 'shell32.pdb',
   'module_offset': '0x782fdb'},
  {'frame': 48,
   'function': 'mozilla::EventStateManager::PreHandleEvent(nsPresContext '
               '*,mozilla::WidgetEvent *,nsIFrame *,nsIContent *,nsEventStatus '
               '*,nsIContent *)',
   'function_offset': '0x18d',
   'module': 'shell32.pdb',
   'module_offset': '0x54430d'},
  {'frame': 49,
   'function': 'nsresult mozilla::PresShell::HandleEventInternal(class '
               'mozilla::WidgetEvent *, nsEventStatus *, bool, class '
               'nsIContent *)',
   'function_offset': '0x19f',
   'module': 'shell32.pdb',
   'module_offset': '0x5418df'}],
 [{'frame': 0,
   'function': 'static long patched_LdrLoadDll(wchar_t *, unsigned long *, '
               'struct _UNICODE_STRING *, void * *)',
   'function_offset': '0x1ec',
   'module': 'mozglue.pdb',
   'module_offset': '0x52fc'},
  {'frame': 1,
   'function': 'LoadLibraryExW',
   'function_offset': '0x17b',
   'module': 'kernelbase.pdb',
   'module_offset': '0x32a7b'},
  {'frame': 2,
   'function': 'QueryHybridDiscreteList(unsigned short *,unsigned int)',
   'function_offset': '0x1c',
   'module': 'dxgi.pdb',
   'module_offset': '0x57f6c'},
  {'frame': 3,
   'function': 'CAdjustEnumForHybrid<CDXGIFactoryWrapper>::AdjustEnumForHybrid()',
   'function_offset': '0x453',
   'module': 'dxgi.pdb',
   'module_offset': '0xa9e3'},
  {'frame': 4,
   'function': 'CDXGIFactory::SampleAdaptersWorker(long '
               '(*)(_D3DKMT_CLOSEADAPTER const *),long '
               '(*)(_D3DKMT_ENUMADAPTERS2 const *),long '
               '(*)(_D3DKMT_QUERYADAPTERINFO const *),long '
               '(*)(_D3DKMT_QUERYVIDEOMEMORYINFO *),void * *)',
   'function_offset': '0x382',
   'module': 'dxgi.pdb',
   'module_offset': '0x12732'},
  {'frame': 5,
   'function': 'CDXGIFactory::SampleAdapters()',
   'function_offset': '0xcd',
   'module': 'dxgi.pdb',
   'module_offset': '0x122f5'},
  {'frame': 6,
   'function': 'CDXGIFactory::Initialize(unsigned int)',
   'function_offset': '0xbb',
   'module': 'dxgi.pdb',
   'module_offset': '0x12a33'},
  {'frame': 7,
   'function': 'CreateDXGIFactoryImpl(unsigned int,IDXGIFactory1 * *)',
   'function_offset': '0x72',
   'module': 'dxgi.pdb',
   'module_offset': '0xc77e'},
  {'frame': 8,
   'function': 'CreateDXGIFactoryActualImpl(_GUID const &,void * *)',
   'function_offset': '0x35',
   'module': 'dxgi.pdb',
   'module_offset': '0x9eb5'},
  {'frame': 9,
   'function': 'CreateDXGIFactory',
   'function_offset': '0x61',
   'module': 'dxgi.pdb',
   'module_offset': '0x9e41'},
  {'frame': 10,
   'function': 'mozilla::widget::GfxInfo::Init()',
   'function_offset': '0xcc9',
   'module': 'xul.pdb',
   'module_offset': '0x138739'},
  {'frame': 11,
   'function': 'static nsresult mozilla::widget::GfxInfoConstructor(class '
               'nsISupports *, const struct nsID & const, void * *)',
   'function_offset': '0x4a',
   'module': 'xul.pdb',
   'module_offset': '0x384a1fa'},
  {'frame': 12,
   'function': 'nsComponentManagerImpl::CreateInstanceByContractID(char const '
               '*,nsISupports *,nsID const &,void * *)',
   'function_offset': '0xa7',
   'module': 'xul.pdb',
   'module_offset': '0x2f2d7'},
  {'frame': 13,
   'function': 'nsComponentManagerImpl::GetServiceByContractID(char const '
               '*,nsID const &,void * *)',
   'function_offset': '0x237',
   'module': 'xul.pdb',
   'module_offset': '0x2efe7'},
  {'frame': 14,
   'function': 'nsCOMPtr_base::assign_from_gs_contractid(nsGetServiceByContractID,nsID '
               'const &)',
   'function_offset': '0x31',
   'module': 'xul.pdb',
   'module_offset': '0x2ed71'},
  {'frame': 15,
   'function': 'XPCOMService_GetGfxInfo',
   'function_offset': '0x69',
   'module': 'xul.pdb',
   'module_offset': '0x15ce99'},
  {'frame': 16,
   'function': 'gfxPlatform::Init()',
   'function_offset': '0x60d',
   'module': 'xul.pdb',
   'module_offset': '0x15abfd'},
  {'frame': 17,
   'function': 'static void CreateVsyncRefreshTimer()',
   'function_offset': '0x96',
   'module': 'xul.pdb',
   'module_offset': '0x3991566'},
  {'frame': 18,
   'function': 'nsRefreshDriver::ChooseTimer()',
   'function_offset': '0x128',
   'module': 'xul.pdb',
   'module_offset': '0x1e0a08'},
  {'frame': 19,
   'function': 'nsRefreshDriver::EnsureTimerStarted(nsRefreshDriver::EnsureTimerStartedFlags)',
   'function_offset': '0x86',
   'module': 'xul.pdb',
   'module_offset': '0x1e0686'},
  {'frame': 20,
   'function': 'nsIPresShell::DoObserveStyleFlushes()',
   'function_offset': '0x81',
   'module': 'xul.pdb',
   'module_offset': '0x1e05b1'},
  {'frame': 21,
   'function': 'nsPresContext::CompatibilityModeChanged()',
   'function_offset': '0x1df',
   'module': 'xul.pdb',
   'module_offset': '0x1e051f'},
  {'frame': 22,
   'function': 'mozilla::PresShell::Init(mozilla::dom::Document '
               '*,nsPresContext *,nsViewManager '
               '*,mozilla::UniquePtr<mozilla::ServoStyleSet,mozilla::DefaultDelete<mozilla::ServoStyleSet> '
               '>)',
   'function_offset': '0x2a8',
   'module': 'xul.pdb',
   'module_offset': '0x1d97e8'},
  {'frame': 23,
   'function': 'mozilla::dom::Document::CreateShell(nsPresContext '
               '*,nsViewManager '
               '*,mozilla::UniquePtr<mozilla::ServoStyleSet,mozilla::DefaultDelete<mozilla::ServoStyleSet> '
               '>)',
   'function_offset': '0x9f',
   'module': 'xul.pdb',
   'module_offset': '0x1d8a1f'},
  {'frame': 24,
   'function': 'nsresult nsDocumentViewer::InitPresentationStuff(bool)',
   'function_offset': '0x7a',
   'module': 'xul.pdb',
   'module_offset': '0x1cb18a'},
  {'frame': 25,
   'function': 'nsresult nsDocumentViewer::InitInternal(class nsIWidget *, '
               'class nsISupports *, const struct '
               'mozilla::gfx::IntRectTyped<mozilla::gfx::UnknownUnits> & '
               'const, bool, bool, bool)',
   'function_offset': '0x325',
   'module': 'xul.pdb',
   'module_offset': '0x1b04a5'},
  {'frame': 26,
   'function': 'nsDocumentViewer::Init(nsIWidget '
               '*,mozilla::gfx::IntRectTyped<mozilla::gfx::UnknownUnits> const '
               '&)',
   'function_offset': '0x21',
   'module': 'xul.pdb',
   'module_offset': '0x1b0171'},
  {'frame': 27,
   'function': 'nsresult nsDocShell::Embed(class nsIContentViewer *, const '
               'char *, class nsISupports *)',
   'function_offset': '0x52d',
   'module': 'xul.pdb',
   'module_offset': '0x1af8fd'},
  {'frame': 28,
   'function': 'nsresult nsDocShell::CreateAboutBlankContentViewer(class '
               'nsIPrincipal *, class nsIURI *, bool, bool)',
   'function_offset': '0x1b6',
   'module': 'xul.pdb',
   'module_offset': '0x181c76'},
  {'frame': 29,
   'function': 'nsresult nsWebShellWindow::Initialize(class nsIXULWindow *, '
               'class nsIXULWindow *, class nsIURI *, int, int, bool, class '
               'nsITabParent *, class mozIDOMWindowProxy *, struct '
               'nsWidgetInitData & const)',
   'function_offset': '0x468',
   'module': 'xul.pdb',
   'module_offset': '0x174aa8'},
  {'frame': 30,
   'function': 'nsresult nsAppShellService::JustCreateTopWindow(class '
               'nsIXULWindow *, class nsIURI *, unsigned int, int, int, bool, '
               'class nsITabParent *, class mozIDOMWindowProxy *, class '
               'nsWebShellWindow * *)',
   'function_offset': '0x1e3',
   'module': 'xul.pdb',
   'module_offset': '0x173c53'},
  {'frame': 31,
   'function': 'nsAppShellService::CreateTopLevelWindow(nsIXULWindow *,nsIURI '
               '*,unsigned int,int,int,nsITabParent *,mozIDOMWindowProxy '
               '*,nsIXULWindow * *)',
   'function_offset': '0x90',
   'module': 'xul.pdb',
   'module_offset': '0x2125d0'},
  {'frame': 32,
   'function': 'nsAppStartup::CreateChromeWindow2(nsIWebBrowserChrome '
               '*,unsigned int,nsITabParent *,mozIDOMWindowProxy *,unsigned '
               '__int64,bool *,nsIWebBrowserChrome * *)',
   'function_offset': '0x10d',
   'module': 'xul.pdb',
   'module_offset': '0x2122fd'},
  {'frame': 33,
   'function': 'nsresult nsWindowWatcher::CreateChromeWindow(const class '
               'nsTSubstring<char> & const, class nsIWebBrowserChrome *, '
               'unsigned int, class nsITabParent *, class mozIDOMWindowProxy '
               '*, unsigned __int64, class nsIWebBrowserChrome * *)',
   'function_offset': '0xb7',
   'module': 'xul.pdb',
   'module_offset': '0x212167'},
  {'frame': 34,
   'function': 'nsresult nsWindowWatcher::OpenWindowInternal(class '
               'mozIDOMWindowProxy *, const char *, const char *, const char '
               '*, bool, bool, bool, class nsIArray *, bool, bool, class '
               'nsDocShellLoadState *, class mozIDOMWindowProxy * *)',
   'function_offset': '0x1757',
   'module': 'xul.pdb',
   'module_offset': '0x20faf7'},
  {'frame': 35,
   'function': 'nsWindowWatcher::OpenWindow(mozIDOMWindowProxy *,char const '
               '*,char const *,char const *,nsISupports *,mozIDOMWindowProxy * '
               '*)',
   'function_offset': '0x12e',
   'module': 'xul.pdb',
   'module_offset': '0x20e37e'},
  {'frame': 36,
   'function': 'XPTC__InvokebyIndex',
   'function_offset': '0x72',
   'module': 'xul.pdb',
   'module_offset': '0x4932922'},
  {'frame': 37,
   'function': 'static bool XPCWrappedNative::CallMethod(class XPCCallContext '
               '& const, XPCWrappedNative::CallMode)',
   'function_offset': '0xa90',
   'module': 'xul.pdb',
   'module_offset': '0xbef70'}],
 [{'frame': 0,
   'function': 'static long patched_LdrLoadDll(wchar_t *, unsigned long *, '
               'struct _UNICODE_STRING *, void * *)',
   'function_offset': '0x1eb',
   'module': 'shcore.pdb',
   'module_offset': '0x51db'},
  {'frame': 1,
   'function': 'LoadLibraryExW',
   'function_offset': '0xb4',
   'module': 'shcore.pdb',
   'module_offset': '0xa3a4'},
  {'frame': 2,
   'function': 'LoadLibraryWithLogging(LoadOrFreeWhy,unsigned short const '
               '*,unsigned long,HINSTANCE__ * *)',
   'function_offset': '0x2c',
   'module': 'shcore.pdb',
   'module_offset': '0x2296c'},
  {'frame': 3,
   'function': 'CClassCache::CDllPathEntry::LoadDll(DLL_INSTANTIATION_PROPERTIES '
               '&,long (*&)(_GUID const &,_GUID const &,void * *),long '
               '(*&)(HSTRING__ *,IActivationFactory * *),long '
               '(*&)(void),HINSTANCE__ * &)',
   'function_offset': '0x74',
   'module': 'shcore.pdb',
   'module_offset': '0x228c4'},
  {'frame': 4,
   'function': 'CClassCache::CDllPathEntry::Create(DLL_INSTANTIATION_PROPERTIES '
               '&,bool,CClassCache::CDllPathEntry * &)',
   'function_offset': '0x43',
   'module': 'shcore.pdb',
   'module_offset': '0x22693'},
  {'frame': 5,
   'function': "[thunk]:CProcessActivator::`vcall'{72,{flat}}' }'",
   'function_offset': '0xe4',
   'module': 'shcore.pdb',
   'module_offset': '0x222a0'},
  {'frame': 6,
   'function': "[thunk]:CProcessActivator::`vcall'{72,{flat}}' }'",
   'function_offset': '0x7c',
   'module': 'shcore.pdb',
   'module_offset': '0x22238'},
  {'frame': 7,
   'function': 'CClassCache::GetClassObject(ACTIVATION_PROPERTIES const &)',
   'function_offset': '0x49',
   'module': 'shcore.pdb',
   'module_offset': '0x21309'},
  {'frame': 8,
   'function': 'CServerContextActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x15b',
   'module': 'shcore.pdb',
   'module_offset': '0x21fcb'},
  {'frame': 9,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x87',
   'module': 'shcore.pdb',
   'module_offset': '0x17677'},
  {'frame': 10,
   'function': 'CApartmentActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x8b',
   'module': 'shcore.pdb',
   'module_offset': '0x21ddb'},
  {'frame': 11,
   'function': 'CProcessActivator::CCICallback(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x4e',
   'module': 'shcore.pdb',
   'module_offset': '0x21e4a'},
  {'frame': 12,
   'function': 'CProcessActivator::AttemptActivation(ActivationPropertiesIn '
               '*,IUnknown *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *,long ( '
               'CProcessActivator::*)(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *),unsigned long)',
   'function_offset': '0x33',
   'module': 'shcore.pdb',
   'module_offset': '0x216ab'},
  {'frame': 13,
   'function': 'ActivationPropertiesIn::GetReturnActivationProperties(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x209',
   'module': 'shcore.pdb',
   'module_offset': '0x21d29'},
  {'frame': 14,
   'function': 'CProcessActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x91',
   'module': 'shcore.pdb',
   'module_offset': '0x22141'},
  {'frame': 15,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x87',
   'module': 'shcore.pdb',
   'module_offset': '0x17677'},
  {'frame': 16,
   'function': 'CClientContextActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x129',
   'module': 'shcore.pdb',
   'module_offset': '0x18499'},
  {'frame': 17,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x87',
   'module': 'shcore.pdb',
   'module_offset': '0x17677'},
  {'frame': 18,
   'function': 'CSplit_QI::CSplit_QI(long &,unsigned long,tagMULTI_QI *)',
   'function_offset': '0x33b',
   'module': 'shcore.pdb',
   'module_offset': '0x1881b'},
  {'frame': 19,
   'function': 'CoCreateInstance',
   'function_offset': '0x1ae',
   'module': 'shcore.pdb',
   'module_offset': '0x122ae'},
  {'frame': 20,
   'function': '_GetServerInfo(unsigned short const *,_GUID const &,unsigned '
               'short *,unsigned int,int *)',
   'function_offset': '0x563',
   'module': 'shcore.pdb',
   'module_offset': '0xa4603'},
  {'frame': 21,
   'function': 'SHExtCoCreateInstance',
   'function_offset': '0x28',
   'module': 'shcore.pdb',
   'module_offset': '0x9bb0c'},
  {'frame': 22,
   'function': 'DCA_SHExtCoCreateInstance',
   'function_offset': '0x3d',
   'module': 'shcore.pdb',
   'module_offset': '0xfbb9d'},
  {'frame': 23,
   'function': 'CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers(CDSA<_GUID> '
               'const *,CDSA<FSIconOverlay> *)',
   'function_offset': '0x130',
   'module': 'shcore.pdb',
   'module_offset': '0xfba30'},
  {'frame': 24,
   'function': 'CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers()',
   'function_offset': '0xa0',
   'module': 'shcore.pdb',
   'module_offset': '0xfb7e8'},
  {'frame': 25,
   'function': 'CImageManager::_ShouldUseIconForItem(IItemImageStore *,int)',
   'function_offset': '0x204',
   'module': 'shcore.pdb',
   'module_offset': '0xfacfc'},
  {'frame': 26,
   'function': 'CFSIconOverlayManager::GetFileOverlayInfo(unsigned short const '
               '*,unsigned long,int *,unsigned long)',
   'function_offset': '0x25',
   'module': 'shcore.pdb',
   'module_offset': '0xc3e8d'},
  {'frame': 27,
   'function': 'CFSFolder::_GetOverlayInfo(_ITEMID_CHILD const *,int '
               '*,unsigned long)',
   'function_offset': '0xe7',
   'module': 'shcore.pdb',
   'module_offset': '0xf8197'},
  {'frame': 28,
   'function': 'CKnownFoldersFolder::_GetOverlayIndex(_ITEMID_CHILD const '
               '*,int *,int)',
   'function_offset': '0x59',
   'module': 'shcore.pdb',
   'module_offset': '0xc5469'},
  {'frame': 29,
   'function': 'CDesktopFolderEnum::QueryInterface(_GUID const &,void * *)',
   'function_offset': '0x31',
   'module': 'shcore.pdb',
   'module_offset': '0xf7f8d'},
  {'frame': 30,
   'function': 'CTaskLock::DispatchQueueItem()',
   'function_offset': '0xee',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x31236'},
  {'frame': 31,
   'function': 'CRunnableTask::Run()',
   'function_offset': '0xa4',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xa6d4'},
  {'frame': 32,
   'function': 'CShellTask::TT_Run(bool *)',
   'function_offset': '0x40',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x193c'},
  {'frame': 33,
   'function': 'DPA_DeletePtr',
   'function_offset': '0xdc',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x153c'},
  {'frame': 34,
   'function': 'CShellTaskThread::s_ThreadProc(void *)',
   'function_offset': '0x33',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x1743'},
  {'frame': 35,
   'function': 'ExecuteWorkItemThreadProc',
   'function_offset': '0xf',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x14af'},
  {'frame': 36,
   'function': 'RtlpTpWorkCallback',
   'function_offset': '0x189',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x132e9'},
  {'frame': 37,
   'function': 'TppWorkerThread',
   'function_offset': '0x581',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x7a62'},
  {'frame': 38,
   'function': 'BaseThreadInitThunk',
   'function_offset': '0x1a',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x1842'},
  {'frame': 39,
   'function': 'static void patched_BaseThreadInitThunk(int, void *, void *)',
   'function_offset': '0x8e',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x5ede'},
  {'frame': 40,
   'function': 'RtlUserThreadStart',
   'function_offset': '0x21',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x3df11'}],
 [{'frame': 0,
   'function': 'static long patched_LdrLoadDll(wchar_t *, unsigned long *, '
               'struct _UNICODE_STRING *, void * *)',
   'function_offset': '0x1eb',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x51db'},
  {'frame': 1,
   'function': 'LoadLibraryExW',
   'function_offset': '0xb4',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xa3a4'},
  {'frame': 2,
   'function': 'LoadLibraryWithLogging(LoadOrFreeWhy,unsigned short const '
               '*,unsigned long,HINSTANCE__ * *)',
   'function_offset': '0x2c',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x2296c'},
  {'frame': 3,
   'function': 'CClassCache::CDllPathEntry::LoadDll(DLL_INSTANTIATION_PROPERTIES '
               '&,long (*&)(_GUID const &,_GUID const &,void * *),long '
               '(*&)(HSTRING__ *,IActivationFactory * *),long '
               '(*&)(void),HINSTANCE__ * &)',
   'function_offset': '0x74',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x228c4'},
  {'frame': 4,
   'function': 'CClassCache::CDllPathEntry::Create(DLL_INSTANTIATION_PROPERTIES '
               '&,bool,CClassCache::CDllPathEntry * &)',
   'function_offset': '0x43',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x22693'},
  {'frame': 5,
   'function': "[thunk]:CProcessActivator::`vcall'{72,{flat}}' }'",
   'function_offset': '0xe4',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x222a0'},
  {'frame': 6,
   'function': "[thunk]:CProcessActivator::`vcall'{72,{flat}}' }'",
   'function_offset': '0x7c',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x22238'},
  {'frame': 7,
   'function': 'CClassCache::GetClassObject(ACTIVATION_PROPERTIES const &)',
   'function_offset': '0x49',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x21309'},
  {'frame': 8,
   'function': 'CServerContextActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x15b',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x21fcb'},
  {'frame': 9,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x87',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x17677'},
  {'frame': 10,
   'function': 'CApartmentActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x8b',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x21ddb'},
  {'frame': 11,
   'function': 'CProcessActivator::CCICallback(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x4e',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x21e4a'},
  {'frame': 12,
   'function': 'CProcessActivator::AttemptActivation(ActivationPropertiesIn '
               '*,IUnknown *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *,long ( '
               'CProcessActivator::*)(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *),unsigned long)',
   'function_offset': '0x33',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x216ab'},
  {'frame': 13,
   'function': 'ActivationPropertiesIn::GetReturnActivationProperties(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x209',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x21d29'},
  {'frame': 14,
   'function': 'CProcessActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x91',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x22141'},
  {'frame': 15,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x87',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x17677'},
  {'frame': 16,
   'function': 'CClientContextActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x129',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x18499'},
  {'frame': 17,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x87',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x17677'},
  {'frame': 18,
   'function': 'CSplit_QI::CSplit_QI(long &,unsigned long,tagMULTI_QI *)',
   'function_offset': '0x33b',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x1881b'},
  {'frame': 19,
   'function': 'CoCreateInstance',
   'function_offset': '0x1ae',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x122ae'},
  {'frame': 20,
   'function': '_GetServerInfo(unsigned short const *,_GUID const &,unsigned '
               'short *,unsigned int,int *)',
   'function_offset': '0x563',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xa4603'},
  {'frame': 21,
   'function': 'SHExtCoCreateInstance',
   'function_offset': '0x28',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x9bb0c'},
  {'frame': 22,
   'function': 'DCA_SHExtCoCreateInstance',
   'function_offset': '0x3d',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xfbb9d'},
  {'frame': 23,
   'function': 'CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers(CDSA<_GUID> '
               'const *,CDSA<FSIconOverlay> *)',
   'function_offset': '0x130',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xfba30'},
  {'frame': 24,
   'function': 'CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers()',
   'function_offset': '0xa0',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xfb7e8'},
  {'frame': 25,
   'function': 'CImageManager::_ShouldUseIconForItem(IItemImageStore *,int)',
   'function_offset': '0x204',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xfacfc'},
  {'frame': 26,
   'function': 'CFSIconOverlayManager::GetFileOverlayInfo(unsigned short const '
               '*,unsigned long,int *,unsigned long)',
   'function_offset': '0x25',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xc3e8d'},
  {'frame': 27,
   'function': 'CFSFolder::_GetOverlayInfo(_ITEMID_CHILD const *,int '
               '*,unsigned long)',
   'function_offset': '0xe7',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xf8197'},
  {'frame': 28,
   'function': 'CKnownFoldersFolder::_GetOverlayIndex(_ITEMID_CHILD const '
               '*,int *,int)',
   'function_offset': '0x59',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xc5469'},
  {'frame': 29,
   'function': 'CDesktopFolderEnum::QueryInterface(_GUID const &,void * *)',
   'function_offset': '0x31',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xf7f8d'},
  {'frame': 30,
   'function': 'CTaskLock::DispatchQueueItem()',
   'function_offset': '0xee',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x31236'},
  {'frame': 31,
   'function': 'CRunnableTask::Run()',
   'function_offset': '0xa4',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xa6d4'},
  {'frame': 32,
   'function': 'CShellTask::TT_Run(bool *)',
   'function_offset': '0x40',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x193c'},
  {'frame': 33,
   'function': 'DPA_DeletePtr',
   'function_offset': '0xdc',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x153c'},
  {'frame': 34,
   'function': 'CShellTaskThread::s_ThreadProc(void *)',
   'function_offset': '0x33',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x1743'},
  {'frame': 35,
   'function': 'ExecuteWorkItemThreadProc',
   'function_offset': '0xf',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x14af'},
  {'frame': 36,
   'function': 'RtlpTpWorkCallback',
   'function_offset': '0x189',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x132e9'},
  {'frame': 37,
   'function': 'TppWorkerThread',
   'function_offset': '0x581',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x7a62'},
  {'frame': 38,
   'function': 'BaseThreadInitThunk',
   'function_offset': '0x1a',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x1842'},
  {'frame': 39,
   'function': 'static void patched_BaseThreadInitThunk(int, void *, void *)',
   'function_offset': '0x8e',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x5ede'},
  {'frame': 40,
   'function': 'RtlUserThreadStart',
   'function_offset': '0x21',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x3df11'}],
 [{'frame': 0,
   'function': 'static long patched_LdrLoadDll(wchar_t *, unsigned long *, '
               'struct _UNICODE_STRING *, void * *)',
   'function_offset': '0x1eb',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x51db'},
  {'frame': 1,
   'function': 'LoadLibraryExW',
   'function_offset': '0xb4',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xa3a4'},
  {'frame': 2,
   'function': 'LoadLibraryWithLogging(LoadOrFreeWhy,unsigned short const '
               '*,unsigned long,HINSTANCE__ * *)',
   'function_offset': '0x2c',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x2296c'},
  {'frame': 3,
   'function': 'CClassCache::CDllPathEntry::LoadDll(DLL_INSTANTIATION_PROPERTIES '
               '&,long (*&)(_GUID const &,_GUID const &,void * *),long '
               '(*&)(HSTRING__ *,IActivationFactory * *),long '
               '(*&)(void),HINSTANCE__ * &)',
   'function_offset': '0x74',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x228c4'},
  {'frame': 4,
   'function': 'CClassCache::CDllPathEntry::Create(DLL_INSTANTIATION_PROPERTIES '
               '&,bool,CClassCache::CDllPathEntry * &)',
   'function_offset': '0x43',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x22693'},
  {'frame': 5,
   'function': "[thunk]:CProcessActivator::`vcall'{72,{flat}}' }'",
   'function_offset': '0xe4',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x222a0'},
  {'frame': 6,
   'function': "[thunk]:CProcessActivator::`vcall'{72,{flat}}' }'",
   'function_offset': '0x7c',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x22238'},
  {'frame': 7,
   'function': 'CClassCache::GetClassObject(ACTIVATION_PROPERTIES const &)',
   'function_offset': '0x49',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x21309'},
  {'frame': 8,
   'function': 'CServerContextActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x15b',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x21fcb'},
  {'frame': 9,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x87',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x17677'},
  {'frame': 10,
   'function': 'CApartmentActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x8b',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x21ddb'},
  {'frame': 11,
   'function': 'CProcessActivator::CCICallback(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x4e',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x21e4a'},
  {'frame': 12,
   'function': 'CProcessActivator::AttemptActivation(ActivationPropertiesIn '
               '*,IUnknown *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *,long ( '
               'CProcessActivator::*)(unsigned long,IUnknown '
               '*,ActivationPropertiesIn *,IActivationPropertiesIn '
               '*,IActivationPropertiesOut * *),unsigned long)',
   'function_offset': '0x33',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x216ab'},
  {'frame': 13,
   'function': 'ActivationPropertiesIn::GetReturnActivationProperties(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x209',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x21d29'},
  {'frame': 14,
   'function': 'CProcessActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x91',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x22141'},
  {'frame': 15,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x87',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x17677'},
  {'frame': 16,
   'function': 'CClientContextActivator::CreateInstance(IUnknown '
               '*,IActivationPropertiesIn *,IActivationPropertiesOut * *)',
   'function_offset': '0x129',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x18499'},
  {'frame': 17,
   'function': 'ActivationPropertiesIn::DelegateCreateInstance(IUnknown '
               '*,IActivationPropertiesOut * *)',
   'function_offset': '0x87',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x17677'},
  {'frame': 18,
   'function': 'CSplit_QI::CSplit_QI(long &,unsigned long,tagMULTI_QI *)',
   'function_offset': '0x33b',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x1881b'},
  {'frame': 19,
   'function': 'CoCreateInstance',
   'function_offset': '0x1ae',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x122ae'},
  {'frame': 20,
   'function': '_GetServerInfo(unsigned short const *,_GUID const &,unsigned '
               'short *,unsigned int,int *)',
   'function_offset': '0x563',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xa4603'},
  {'frame': 21,
   'function': 'SHExtCoCreateInstance',
   'function_offset': '0x28',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x9bb0c'},
  {'frame': 22,
   'function': 'DCA_SHExtCoCreateInstance',
   'function_offset': '0x3d',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xfbb9d'},
  {'frame': 23,
   'function': 'CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers(CDSA<_GUID> '
               'const *,CDSA<FSIconOverlay> *)',
   'function_offset': '0x130',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xfba30'},
  {'frame': 24,
   'function': 'CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers()',
   'function_offset': '0xa0',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xfb7e8'},
  {'frame': 25,
   'function': 'CImageManager::_ShouldUseIconForItem(IItemImageStore *,int)',
   'function_offset': '0x204',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xfacfc'},
  {'frame': 26,
   'function': 'CFSIconOverlayManager::GetFileOverlayInfo(unsigned short const '
               '*,unsigned long,int *,unsigned long)',
   'function_offset': '0x25',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xc3e8d'},
  {'frame': 27,
   'function': 'CFSFolder::_GetOverlayInfo(_ITEMID_CHILD const *,int '
               '*,unsigned long)',
   'function_offset': '0xe7',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xf8197'},
  {'frame': 28,
   'function': 'CKnownFoldersFolder::_GetOverlayIndex(_ITEMID_CHILD const '
               '*,int *,int)',
   'function_offset': '0x59',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xc5469'},
  {'frame': 29,
   'function': 'CDesktopFolderEnum::QueryInterface(_GUID const &,void * *)',
   'function_offset': '0x31',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xf7f8d'},
  {'frame': 30,
   'function': 'CTaskLock::DispatchQueueItem()',
   'function_offset': '0xee',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x31236'},
  {'frame': 31,
   'function': 'CRunnableTask::Run()',
   'function_offset': '0xa4',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0xa6d4'},
  {'frame': 32,
   'function': 'CShellTask::TT_Run(bool *)',
   'function_offset': '0x40',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x193c'},
  {'frame': 33,
   'function': 'DPA_DeletePtr',
   'function_offset': '0xdc',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x153c'},
  {'frame': 34,
   'function': 'CShellTaskThread::s_ThreadProc(void *)',
   'function_offset': '0x33',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x1743'},
  {'frame': 35,
   'function': 'ExecuteWorkItemThreadProc',
   'function_offset': '0xf',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x14af'},
  {'frame': 36,
   'function': 'RtlpTpWorkCallback',
   'function_offset': '0x189',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x132e9'},
  {'frame': 37,
   'function': 'TppWorkerThread',
   'function_offset': '0x581',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x7a62'},
  {'frame': 38,
   'function': 'BaseThreadInitThunk',
   'function_offset': '0x1a',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x1842'},
  {'frame': 39,
   'function': 'static void patched_BaseThreadInitThunk(int, void *, void *)',
   'function_offset': '0x8e',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x5ede'},
  {'frame': 40,
   'function': 'RtlUserThreadStart',
   'function_offset': '0x21',
   'module': 'ExplorerFrame.pdb',
   'module_offset': '0x3df11'}]

      ]